### ISSUE TITLE
Fetch currently installed APK from device itself

### ISSUE THREAD

**Issue by raisehero** [Aliucord/Aliucord#110]
### What is it that you'd like to see?

I'm pretty sure file manager allow you to copy the APK currently installed on the device to Internal Storage without root.

### Go into more detail...

This would avoid downloading Discord APK again.

### Request Agreement

- [X] I did indeed check to make sure my feature request is original!

**Comment by Hades785** [comment]
That's already a feature of the installer.
It's not shown by default because more than likely the Discord version locally installed won't be the same that is used by Aliucord. Aliucord only officially supports one Discord version at a time, to avoid issues arising from multiple versions having different sets of features and or not working because of obfuscation changes.

**Comment by Vendicated** [comment]
already exists. we hid it behind a switch because people kept installing the wrong discord version

 installer settings > developer mode
