### ISSUE TITLE
[Feature Request] Android 6.0.1 support

### ISSUE THREAD

**Issue by SwiftyPop** [Aliucord/Aliucord#190]
### What is it that you'd like to see?

Hoping to get Android 6.0.1 supported. Im pretty broke to buy new phone.

**Comment by zt64** [comment]
This is more of an issue for Pine, and its not likely to ever happen

**Comment by ItzOnlyAnimal** [comment]
Just use a custom rom :)

they're probably better for your old phone situation anyway

**Comment by Juby210** [comment]
Pine works on android 6, but you have to have arm64 phone which is very most likely on that old android versions. Anyways supporting that old versions causes a lot of pain and for example loading plugin resources doesn't work because it just doesn't:tm:

So yeah just get a custom rom or eventually get a newer phone
![image](https://user-images.githubusercontent.com/31005896/147910022-fcd210eb-17d6-45cd-a4b5-c0b011cfcb06.png)
