### ISSUE TITLE
Notification dosen't work

### ISSUE THREAD

**Issue by TotallyHuman675** [Aliucord/Aliucord#211]
### Discord Account

TotallyHuman#0675

### What happens when the bug or crash occurs?

The in-app notification works fine but when i exit the app no matter if its open in the background or not, the notifications dosent work at all, it dosent make a sound, vibrate, or has a pop up

### What is the expected behaviour?

It rarely works but most of the it dosent. And yes i have ckecked the app setting, it is all on and i have checked the setting in app, and it's all enabled

### How do you recreate this bug or crash?

Unrecreatable, it almost always happens

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Juby210** [comment]
We can't really help you with that. Notifications are handled by google services - firebase.

**Comment by TotallyHuman675** [comment]
> We can't really help you with that. Notifications are handled by google services - firebase.

Well is there a way for me to fix it?, because it seemed that not many other people are having this problem

**Comment by Vendicated** [comment]
If you have discord open on pc that is why. If you are, discord delays notifications to your phone by 10 minutes. Solutions are closing discord on desktop or staying idle for more than 10 minutes.

Otherwise, make sure you have Google play services or microg installed and that they're working correctly and your phone isn't on do not disturb
