### ISSUE TITLE
Android 6

### ISSUE THREAD

**Issue by An-undertale-fan** [Aliucord/Aliucord#221]
### Discord Account

an UNDERTALE Fan#3904

### What happens when the bug or crash occurs?

I open it and just crash
I didn't do anything to make it crash
Ir might be because im using android 6 or it doesn't work on my phone "oppo A57" 

### What is the expected behaviour?

I downloaded aliucord and open it crash Allways 

### How do you recreate this bug or crash?

Just opened the app

### Crash-log

```
If open it serval time it say "aliucord has failed to startup multiple time, clearing the history might fix ut" but it didn't, this message was from the android system not the app
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Juby210** [comment]
Read the readme. It clearly says that Aliucord is for Android 7 - 13

**Comment by NotHuza** [comment]
plase add supmort for android 6.0 i even do adb logcat

06-26 21:48:48.861 29310 29310 E AndroidRuntime: Process: com.aliucord, PID: 29310
06-26 21:48:48.861 29310 29310 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.discord.app.App: java.lang.ClassNotFoundException: Didn't find class "com.discord.app.App" on path: DexPathList[[zip file "/data/app/com.aliucord-1/base.apk"],nativeLibraryDirectories=[/data/app/com.aliucord-1/lib/arm, /data/app/com.aliucord-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:622)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4794)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.app.ActivityThread.access$1600(ActivityThread.java:157)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5551)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
06-26 21:48:48.861 29310 29310 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.discord.app.App" on path: DexPathList[[zip file "/data/app/com.aliucord-1/base.apk"],nativeLibraryDirectories=[/data/app/com.aliucord-1/lib/arm, /data/app/com.aliucord-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:982)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:617)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        ... 9 more
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.aliucord-1/base.apk
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.DexFile.openDexFileNative(Native Method)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.DexFile.openDexFile(DexFile.java:295)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:80)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.DexFile.<init>(DexFile.java:59)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:279)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.DexPathList.<init>(DexPathList.java:120)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at android.app.LoadedApk.getClassLoader(LoadedApk.java:420)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at android.app.LoadedApk.makeApplication(LoadedApk.java:612)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                ... 9 more
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        Suppressed: java.lang.ClassNotFoundException: com.discord.app.App
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at java.lang.Class.classForName(Native Method)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-26 21:48:48.861 29310 29310 E AndroidRuntime:                ... 12 more
06-26 21:48:48.861 29310 29310 E AndroidRuntime:        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
06-26 21:48:54.175 29334 29334 E AndroidRuntime: FATAL EXCEPTION: main

**Comment by DiamondMiner88** [comment]
> plase add supmort for android 6.0
please update to android 7+

**Comment by NotHuza** [comment]
> > plase add supmort for android 6.0
> > please update to android 7+

i cant i only can buy new phone i will use bluecord behause bluecord work but alucord is beeter and i use alucord in device with broken screen with android 9.0
i need use one year my old device before i buy new phone

**Comment by GangsterFox** [comment]
Just use custom ROMs...
Anyhow we dont support anything under android 7
