### ISSUE TITLE
I can't join the Aliucord Discord server

### ISSUE THREAD

**Issue by ilexite** [Aliucord/Aliucord#235]
### Discord Account

ilexite#1488

### What happens when the bug or crash occurs?

Nothing. I type the invite and press join and nothing happens; I do not join the server.

### What is the expected behaviour?

I expect to be in the server.

### How do you recreate this bug or crash?

1. Be me
2. Try to join
3. Fail

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by ilexite** [comment]
Also, there is no "User is banned from this guild" toast so I don't believe I am banned, and I don't see a reason that I should be; I've never been in the server before.

**Comment by GangsterFox** [comment]
First of all, wrong repo to ask this
Second of all, you have been probably banned due to your account not being older than 2 days(we automatically ban them as a security measure) 

Could you state the accounts ID which you think is banned
Since the account you wrote is not banned, maybe another account you used got banned

**Comment by ilexite** [comment]
This is the only account I used, the ID is 922246734527213690. I did however try to join on a public network, where someone could have gotten banned.

**Comment by GangsterFox** [comment]
I checked again via the ID, you are in fact not banned
Try switching networks and try again

**Comment by ilexite** [comment]
I tried on a different network, I'm having the same issue.
