### ISSUE TITLE
Not able to join support server

### ISSUE THREAD

**Issue by learnereren31** [Aliucord/Aliucord#464]
### Discord Account

itachii_uchiha21

### What happens when the bug or crash occurs?

Hello whenever i hit join button in app nothing works and i tried on web too but there its showing unable to accept invite(fyi - im able to join other server no restriction no limit) its just happening with Aliucord.
![IMG_20240711_040427_056](https://github.com/Aliucord/Aliucord/assets/169615239/5783eede-e8bf-42dd-b7a4-8f07766544a5)

### What is the expected behaviour?

I expect to join the server 

### How do you recreate this bug or crash?

Create new discord account and try to join aliucord server and check if its working.

### Crash-log

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by rushiiMachine** [comment]
you were banned most likely for due to a new account

**Comment by learnereren31** [comment]
> you were banned most likely for due to a new account 

But im able to join other servers so my account is banned on aliucord? Could please check username i provided? Thanks

**Comment by rushiiMachine** [comment]
unbanned

**Comment by learnereren31** [comment]
Thanks a lot ❤️

**Comment by wwwwwwari** [comment]
@rushiiMachine Hello, I'm aware I shouldn't leave a comment like this in a closed issue, but I can't seem to find any other ways to contact anyone who could help me at all. If I should contact someone else in a different platform, please let me know.

I'm also banned for having a new Discord account. I used to have an older Discord account, but decided to abandon it due to an unrelated personal issue. 

Could you please unban me? My account is nonomiya_himawari. The only thing I want from the server is to access the plugin list, so I won't be bothering anyone or breaking any rules.

To prove that I'm not some spammer, you can view some of my GitHub activities and my Mastodon account (though it's not really that active).

**Comment by rushiiMachine** [comment]
done
