### ISSUE TITLE
Update not installing

### ISSUE THREAD

**Issue by 4uncuk** [Aliucord/Aliucord#493]
### What happens when the bug or crash occurs?

The app tells me that 126.21 is available to for download but wnen i do update my app, the thing doesn't disappear. I can update infinitely and nothing changes. Also, i cannot change my profile stuff, pfp and other stuff.
When i try to join you guys's dc server, it tells me that the invite is invalid.
Im wondering if y'all are even working on this app 

### What is the expected behaviour?

Just update your app and make it work

### How do you recreate this bug or crash?

¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

### Crash-log

Dont have one

### Request Agreement

- [X] I did indeed check to make sure the bug or crash report is applicable!

**Comment by Juby210** [comment]
126.21 is latest version of Discord we support (it is not Aliucord version, but Discord version!), because it is last version that doesn't use React Native framework, we can't update to newer versions, as it uses entirely different code (it is just ported from iOS xD and also works way worse on Android devices (the performance of new Discord app is horrible on non-flagships)). 

> the thing doesn't disappear

what even is "the thing"

> Also, i cannot change my profile stuff, pfp and other stuff.

Editing profiles is not backported from newer Discord versions, as editing profile isn't something you need to do often.
126.21 Discord is from 2022, so it doesn't have all of new Discord features by default. 

> When i try to join you guys's dc server, it tells me that the invite is invalid.

You tried to join with an alt and we don't allow new Discord accounts, so you got automatically banned. Just join with your normal account or give us your Discord account ID (not username) for unban.

 > Im wondering if y'all are even working on this app
 
 Yes we are, but this is just a hobby project, you don't pay us for making it. And the core functionality (this is just a chat app after all) still works perfectly fine.
 
 > Just update your app and make it work
 
Maybe you do it? :) It is not that easy and requires time and effort to add features that aren't very useful for a chat app.

**Comment by 4uncuk** [comment]
> 126.21 is latest version of Discord we support (it is not Aliucord version, but Discord version!), because it is last version that doesn't use React Native framework, we can't update to newer versions, as it uses entirely different code (it is just ported from iOS xD and also works way worse on Android devices (the performance of new Discord app is horrible on non-flagships)).
> 
> > the thing doesn't disappear
> 
> what even is "the thing"
> 
> > Also, i cannot change my profile stuff, pfp and other stuff.
> 
> Editing profiles is not backported from newer Discord versions, as editing profile isn't something you need to do often. 126.21 Discord is from 2022, so it doesn't have all of new Discord features by default.
> 
> > When i try to join you guys's dc server, it tells me that the invite is invalid.
> 
> You tried to join with an alt and we don't allow new Discord accounts, so you got automatically banned. Just join with your normal account or give us your Discord account ID (not username) for unban.
> 
> > Im wondering if y'all are even working on this app
> 
> Yes we are, but this is just a hobby project, you don't pay us for making it. And the core functionality (this is just a chat app after all) still works perfectly fine.
> 
> > Just update your app and make it work
> 
> Maybe you do it? :) It is not that easy and requires time and effort to add features that aren't very useful for a chat app.

The "thing" is the "supported version" text in aliucord installer
I got banned on discord about 6 months ago, and i couldn't create a new account. But now i did, so it's new, and isnt my alt account. Userid: 1297289242686525611
Hope i get unbanned

Anyways, thanks

**Comment by Juby210** [comment]
> The "thing" is the "supported version" text in aliucord installer

Why would it go away after installing?? It doesn't say that's an update, it just says what's the supported version of Discord for Aliucord.

Anyway unbanned, you can join now.
